name: Problems 1-100

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install dependencies
              run: cargo install cargo-audit
            - name: Build
              run: cargo build --verbose --all
            - name: Test
              run: cargo test --verbose --all
            - name: Clippy
              run: cargo clippy --all-targets --all-features -- -D warnings
            - name: Format
              run: cargo fmt --all -- --check
            - name: Audit
              run: cargo audit
            
            